feature/issue-10-Wallet_with_beacon-sdk (готово)
AndreiBelokopytov/panda-options pull request #12
Opened 2022-02-21 08:55 UTC by ValesValesskiy

Перенёс хук useWallet на beacon-sdk, добавил метод disconnect и покрасил кнопку, создав тему на chakra-ui.

2022-02-21 11:04 UTC, AndreiBelokopytov requested changes
Функционал becon реализован 🥳
Чтобы поправить ошибки, нужно установить плагин ESLint. 
Также нужно обратить внимание на ошибку, из -за которой при подключенном кошельке первоначально на кнопке отображается надпись "Connect" вместо адреса.

2022-02-21 11:04 UTC, AndreiBelokopytov commented on src/hooks/TempleWallet/useWallet.ts
> +      isConnected: connected,
логическая ошибка
`const isConnected = Boolean(permissions?.accountInfo ?? accountInfoCheck.accountInfo)`

2022-02-21 11:06 UTC, AndreiBelokopytov commented on src/hooks/TempleWallet/useWallet.ts
> +  dAppClient
эту функцию нужно обернуть в `useEffect`, чтобы она выполнялась единожды

2022-02-21 11:46 UTC, ValesValesskiy commented on src/hooks/TempleWallet/useWallet.ts
> +  dAppClient
Не совсем понял какую функцию. Если речь о "await dAppClient.clearActiveAccount();", то она внутри хука находится.

2022-02-21 11:54 UTC, ValesValesskiy commented on src/hooks/TempleWallet/useWallet.ts
> +  }, [accountInfoCheck.isInitialized, accountInfoCheck.accountInfo]);
Мне почему Lint ничего не пишет по поводу зависимостей. Что именно ты видишь?

2022-02-21 12:30 UTC, AndreiBelokopytov commented
> Не понял. Там же connected завязано на событие. Когда происходит вход или выход из аккаунта. 

хук `useCheckAccount` выполняется еще до этого события, из-за этого кнопка может неправильно отображаться. Нужно разобраться в очередности выполнения хуков и срабатывания события.

2022-02-21 12:32 UTC, AndreiBelokopytov commented on src/hooks/TempleWallet/useWallet.ts
> +  dAppClient
`.subscribeToEvent`, подписка на событие должна выполняться только один раз. Кроме того, нужно отписываться от событие при отмонтировании компонента, чтобы предотвратить утечку памяти.

2022-02-21 16:04 UTC, AndreiBelokopytov requested changes
Нужны исправления + не все исправлено с предыдущего ревью

2022-02-21 16:04 UTC, AndreiBelokopytov commented on src/hooks/TempleWallet/useWallet/checkActiveAccount.ts
> +export const checkActiveAccount = async (dAppClient: DAppClient) => {
В принципе, даже необязательно выносить в отдельную функцию

2022-02-21 16:12 UTC, AndreiBelokopytov requested changes
+ добавил комментарии по неймингу

2022-02-21 16:12 UTC, AndreiBelokopytov commented on src/hooks/TempleWallet/useWallet/useWallet.ts
> +  const [activeAccountChecked, setActiveAccountChecked] = useState(false);
чтобы не было запутывания имен, нужно назвать `isInitialized, setInitialized` соответственно

2022-02-21 16:12 UTC, AndreiBelokopytov commented on src/hooks/TempleWallet/useWallet/useWallet.ts
> +  const [connected, setConnected] = useState(false);
чтобы не было запутывания имен, следует назвать `isConnected`

2022-02-22 18:35 UTC, AndreiBelokopytov approved these changes

2022-02-22 18:36 UTC, AndreiBelokopytov commented
Finish issue #10

2022-02-22 18:37 UTC, merged